version: '3'

services:
  db-monolith:
    image: postgres:15.1
    container_name: db-monolith
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=master
    volumes:
      - ./db/master/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    ports:
      - "5433:5432"
networks:
  app-network: