version: '3'

services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=master
    volumes:
      - ./db/master/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    ports:
      - "5432:5432"
  monolith:
    image: ghcr.io/iakovalenko-highload-architect/monolith:latest
    container_name: monolith
    restart: unless-stopped
    volumes:
      - ./.env:/project/.env
    networks:
      - app-network
    ports:
      - "8080:8080"
networks:
  app-network: